---
name: Main

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Test
        run: |
          npm ci
          npm run build
          npm test
          bash <(curl -s https://codecov.io/bash)

  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Lint
        run: |
          npm ci
          npm run lint

  publish:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Build and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "Github actions"
          npm ci
          npm run publish
